export const verbs = [
  "sharing",
  "driving",
  "supporting",
  "driving",
  "capturing",
  "collaborating towards",
  "delivering",
  "strengthening",
  "empowering",
  "planning",
  "planning for",
  "leveraging",
  "programming",
  "programming for",
  "integrating",
  "re-structuring",
  "up-scaling",
  "harmonising",
  "facilitating",
  "innovating for",
  "accelerating",
  "catalysing",
  "engaging in",
  "promoting",
  "advancing",
  "promoting",
  "collectively advancing",
  "unleashing",
  "achieving",
  "catalysing collaboration for",
  "leveraging local expertise towards",
  "systematising",
  "connecting",
  "solidarity-building through",
  "building solidarity across",
  "envisioning",
  "empowering",
  "universalising",
  "providing critical support towards",
  "adopting",
  "defending",
  "resourcing",
  "creating",
  "safeguarding",
  "mainstreaming",
  "harnessing",
  "influencing",
  "spearheading",
  "strategising for",
  "affecting",
  "building",
  "capacitating",
  "leveraging",
  "co-harnessing",
  "co-resourcing",
  "co-adopting",
  "co-delivering",
  "co-facilitating",
  "building",
  "workshopping",
  "co-planning",
  "co-creating",
  "mobilising",
  "enabling",
  "co-enabling",
  "cultivating",
  "co-cultivating"
];

export const adjectives = [
  "exploratory",
  "data-driven",
  "sustainable",
  "impactful",
  "accountable",
  "inclusive",
  "sustainable",
  "systematically integrated",
  "systematically controlled",
  "strategically maximised",
  "radically motivated",
  "grassroots",
  "sectoral",
  "urban",
  "democratically programmed",
  "democratically maximised",
  "sustainably mobilised",
  "inclusively formulated",
  "functional",
  "gender-aware",
  "gender-inclusive",
  "cohesive",
  "country-led",
  "sector-wide",
  "innovative",
  "disability inclusive",
  "people-centered",
  "highly leveraged",
  "participatory",
  "in-country",
  "transparent",
  "systemic",
  "transformative",
  "global",
  "intersectional",
  "dynamic",
  "locally-driven",
  "rights-based",
  "resilient",
  "successful",
  "multi-layered",
  "both vertical and horizontal",
  "positive",
  "movement-building",
  "community-led",
  "organic and indigenous",
  "evidence-based",
  "bottom-up",
  "woman-headed",
  "pro-poor",
  "strategic",
  "holistic",
  "technical",
  "cross-cutting",
  "ground-truthed",
  "scalable",
  "stakeholder",
  "trade-offs for",
  "toolkits for",
  "partnerships for",
  "locally-engaged",
  "women-led",
  "community-based",
  "needs-based",
  "context-specific",
  "decisive"
];

export const nouns = [
  "transformations",
  "methodologies",
  "platforms",
  "programmes",
  "journeys",
  "impacts",
  "results",
  "change",
  "civil society",
  "participation",
  "incentives",
  "processes",
  "packages",
  "schemes",
  "initiatives",
  "approaches",
  "objectives",
  "collaboration",
  "strategies",
  "deliverables",
  "catalytic change",
  "conditionality",
  "game changers",
  "paradigm shifts",
  "capacity-building",
  "governance",
  "technical assistance",
  "equity investments",
  "community-building",
  "systems and structures",
  "visions for people and planet",
  "global networks",
  "movement building",
  "livelihoods",
  "community resilience",
  "nation-building",
  "network-building",
  "social capital",
  "programmes",
  "programming",
  "leadership",
  "advocacy",
  "theories of change",
  "gender equality",
  "practices",
  "capacities for change",
  "agents of change",
  "accountability",
  "relational partnerships",
  "poverty reduction",
  "learnings",
  "citizen involvement",
  "best practice",
  "cross-fertilisation",
  "country ownership",
  "empowerment",
  "good governance",
  "human capital",
  "innovations",
  '"development"',
  "development",
  "systemic change",
  "success",
  "transformational change",
  "institution-building",
  "community empowerment",
  "strategic transition",
  "capacity development",
  "long-term change",
  "local capacity",
  "pillars of change",
  "proficiencies",
  "delivery capability"
];
